version: 1.0.1.{build}
skip_tags: true
configuration: Release
platform: x86
install:
- git submodule init
- git submodule update
build:
  project: LogCleaner.sln
  verbosity: minimal
artifacts:
- path: LogCleaner\bin\Release
  name: LogCleaner_Stable
deploy:
- provider: GitHub
  tag: LogCleaner-v$(appveyor_build_version)
  release: LogCleaner-v$(appveyor_build_version)
  description: AppVeyorで自動リリースはじめました
  auth_token:
    secure: FZGlOzjXOlI70ZNfll82No7ADk6X0UClnOhb3xoiRm9UEnTpFI3L3zDfNNdW357L
  artifact: LogCleaner\bin\Release
  draft: false
  prerelease: false
  on:
    branch: /master/
